spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:vrv@1234}
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 10       # 连接池中的最小空闲连接
server:
  tomcat:
    max-connections: 2000
    accept-count: 1000
    threads:
      max: 1000
      min-spare: 300

# 日志打印级别
logging:
  level:
    com.vrv.vap: info
    root: info
    com.alibaba.nacos: ERROR

# 打开所有 Actuator 服务
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  # include: health,info
  endpoint:
    health:
      show-details: always
  # 名称定义
  metrics:
    tags:
      application: ${spring.application.name}
  security:
    enabled: false