spring:
  datasource:
    druid:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/master?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/slave?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:vrv@1234}
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 10       # 连接池中的最小空闲连接

# tomcat 配置调优
server:
  tomcat:
    max-connections: 2000
    accept-count: 1000
    threads:
      max: 1000
      min-spare: 300

# mybatis相关配置
mapper:
  identity: MYSQL
  mappers: com.vrv.vap.db.basemapper.BaseBatisMapper
  not-empty: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    lazy-load-trigger-methods: equals,clone,hashCode
    lazy-loading-enabled: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vrv.vap.*.entity,;com.vrv.vap.*.model

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
restart:
  include:
    mapper: /mapper-[\w-\.]+jar
    pagehelper: /pagehelper-[\w-\.]+jar

# 日志打印级别
logging:
  level:
    com.vrv.vap: info
    root: info
    com.alibaba.nacos: ERROR

# 打开所有 Actuator 服务
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  # include: health,info
  endpoint:
    health:
      show-details: always
  # 名称定义
  metrics:
    tags:
      application: ${spring.application.name}
  security:
    enabled: false